### ISSUE TITLE
How to remove ES if there is only one version installed and in use

### ISSUE THREAD

**Issue by anhlqn** [elasticsearchvn/evm#1]
```
anh@ubuntu:~$ evm version
2.4.0
anh@ubuntu:~$ evm remove 2.4.0
Could not remove Elasticsearch 2.4.0, it is in use.
```
Is there an "unuse" command?

**Comment by duydo** [comment]
No, switch to use other version first then remove 2.4.0.
When using evm I think we intend to play with multiple versions, do you think we need "unuse" command?

**Comment by anhlqn** [comment]
What if I want to remove the last installed version when I no longer need to have ES on my machine? Maybe a `evm remove all` is useful.

**Comment by duydo** [comment]
To uninstall evm, just remove folder ~/.evm `rm -rf ~/.evm` ;-)
